### ISSUE TITLE
Ask Dr. Sampson what either side of the direct region is called.

### ISSUE THREAD

**Issue by mjswensen** [pcnsuite/pcnspec#4]

**Comment by Xerse54** [comment]
I spoke to Dr. Sampson about this nomenclature.  He said terms like producer-lead direct interaction, customer-lead direct interaction, and shared direct interaction.  He used a dancing analogy: the producer is leading the dance (interaction), the custom is leading, or it is shared.

I suggest that we call them direct_leading and direct_shared.  Leading implies that it is on that domain's side.  Shared implies that it is in the middle of the direct interaction area.

**Comment by rahboo15** [comment]
That's a good analogy.  I agree with Phil's idea, except maybe shorten
direct_leading to direct_lead
